spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100   # fetch join 설정

  data:
    web:
      pageable:
        default-page-size: 10   # Pageable Global 설정
        max-page-size: 2000

#logging:
#  level:
#    org.hibernate.SQL: info
